### ISSUE TITLE
Include a requirements.txt file

### ISSUE THREAD

**Issue by xhemals** [jolpica/jolpica-f1#115]
it would be much more user friendly to have a requirements.txt file for all the python modules needed to run this

**Comment by jolpica** [comment]
Hey, we use Poetry and poetry.lock for managing required python dependencies.

Feel free to check it out here: https://python-poetry.org/

Using a lockfile such as poetry.lock (or uv.lock) is much better for keeping strict requirements and managing transitive dependencies. You can also see the list of required dependencies inside pyproject.toml if you don't wish to use poetry.

To get started with installing the project, simply install poetry then run poetry install in the root of the project to get all the required dependencies.

**Comment by xhemals** [comment]
My apologies! Never used poetry before
