### ISSUE TITLE
Inconsistencies when filtering by finishing status

### ISSUE THREAD

**Issue by theOehrly** [jolpica/jolpica-f1#15]
When filtering by finishing status (``/status/<n>``), the results are implausible in some cases.

Milestone is TBD depending on what turns out to be the cause here.

### Affected endpoints

At least 'drivers', 'constructors', 'circuits', 'status', potentially more

### Affected status values (2023)

The following four status filters produce incorrect/implausible results. The problems are different for each filter value.

- ``/status/3``
- ``/status/23``
- ``/status/31``
- ``/status/130``

### Example
- http://api.jolpi.ca/ergast/f1/2023/status/23.json returns ``count: "2"`` but filtering by status 23 on the circuits endpoint returns three total results (http://api.jolpi.ca/ergast/f1/2023/status/23/circuits.json). This should not be possible.

- http://ergast.com/api/f1/2023/status/3/drivers.json returns a total of 8 results, Alonso is not included here. 
http://api.jolpi.ca/ergast/f1/2023/status/3/drivers.json includes Alonso, which is correct because Alonso is listed as "withdrew" in round 19, Mexico. ("withdrew" has status id 3).
Additionally, http://api.jolpi.ca/ergast/f1/2023/status/3/drivers/alonso/circuits.json returns Spa as single result. But Alonso finished the Belgian GP and did not retire there (instead, he retired in Mexico). Spa is then also included when querying for circuits where Alonso finished http://api.jolpi.ca/ergast/f1/2023/status/1/drivers/alonso/circuits.json which is correct. 

### Ideas

I haven't managed to really make sense of this so far. It seems like there are inconsistencies here in Ergast and in the new API. But those inconsistencies are not the same.

My best guess at the moment is that something during the data import goes wrong when trying to correct some of these inconsistencies.

Notably, all four problematic status endpoints include the digit "3" which might point towards a problematic search/replace or regex. But there are other status values in the 2023 season that include the digit "3" but don't cause any issues.

**Comment by jolpica** [comment]
I think I've figured this one out.
The /status endpoint was only counting race results, but the filter for other endpoints was counting sprint races.
