### ISSUE TITLE
Create basic tests for validating parity with Ergast

### ISSUE THREAD

**Issue by chrisfree** [jolpica/jolpica-f1#31]
It was suggested on today's status call to create some basic and automated testing scripts to help validate that we've reached feature parity with Ergast and to ensure that while we are fixing items during beta testing that we don't inadvertently introduce regressions.

**Comment by jolpica** [comment]
I think this can be closed as we already have tests comparing against ergast responses for parity and preventing regression.
See here: [tests/fixtures/ergast_responses](https://github.com/jolpica/jolpica-f1/tree/main/tests/fixtures/ergast_responses)
