### ISSUE TITLE
Sprint weekends contain incorrect additional session on races endpoint

### ISSUE THREAD

**Issue by theOehrly** [jolpica/jolpica-f1#58]
**Describe the bug**
#51 attempted to fix the representation of sprint weekends in the races endpoint. While the "SprintQualifying" entry now exists, the "SecondPractice" entry still exists. Sprint weekends do not have a second practice, though. It seems like this got lost during refactoring.

**To Reproduce**
http://localhost:5000/ergast/f1/2024/5.json

**Expected behavior**
The entry for second practice should not be included.

**Screenshots**
![grafik](https://github.com/user-attachments/assets/774c4452-ab1c-4a2d-83d2-0f004372774a)

**Comment by jolpica** [comment]
I think this is actually intended functionality, but an issue with the data.

Looks like the import script creates a practice 2 and a sprint quali.
<img width="1098" alt="image" src="https://github.com/user-attachments/assets/fa17e707-f90c-4ff6-afcd-f875801ab442">

This ticket can be to fix the underlying data.
