### ISSUE TITLE
[Bug]: Current Driverstandings gives a 500 error

### ISSUE THREAD

**Issue by marcokreeft87** [jolpica/jolpica-f1#77]
### Description

When going to https://api.jolpi.ca/ergast/f1/current/driverStandings.json I get a 500 error

### Affected URL

api.jolpi.ca/ergast/f1/current/driverStandings.json

### To Reproduce

Go to https://api.jolpi.ca/ergast/f1/current/driverStandings.json

### Expected Behavior

No 500 error but json response

**Comment by jolpica** [comment]
Thanks for reporting, issue should be resolve now :)
