### ISSUE TITLE
[Data Correction]: Franco Colapinto's driverId and familyName has a space at the end of it

### ISSUE THREAD

**Issue by nirbhaykwatra** [jolpica/jolpica-f1#79]
### Endpoint

driverStandings

### URL

https://api.jolpi.ca/ergast/f1/2024/driverstandings/?offset=18&limit=1

### What is the current Value?

```shell
{"driverId": "colapinto "}
{"familyName": "Colapinto "}
```

### What should the value be?

```shell
{"driverId": "colapinto"}
{"familyName": "Colapinto"}
```

### Description

The "driverId" and "familyName" values on Franco Colapinto's Driver object have a space at the end, making it necessary to strip the space out before using the data in other contexts. This issue exists on the "drivers" endpoint as well and seems to be a one-off issue.

**Comment by jolpica** [comment]
Thanks for reporting this, this should be resolved now.

**Comment by nirbhaykwatra** [comment]
Thanks for the quick fix!
