### ISSUE TITLE
Historical Seasons have incorrect position and points data

### ISSUE THREAD

**Issue by jolpica** [jolpica/jolpica-f1#84]
All results for the constructor  standings of 1950 have 0 points and no position

https://api.jolpi.ca/ergast/f1/1950/constructorstandings/?limit=1

Investigate and fix this issue in `constructorstandings` & `driverstandings`.

**Comment by MattMaginniss** [comment]
I think this would be intended as prior to 1958 there was no Constructors Championship.

So it makes sense that there are no points and positions for the seasons prior to 1958

**Comment by jolpica** [comment]
Yeap, my current implementation is correct. Completely forgot about that.
